### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by erickmendonca** [nadineproject/nadine#107]
I'm having trouble using special characters, like "ç" for example.

StackTrace:
DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128). You passed in <Member: [Bad Unicode data]> (<class 'staff.models.Member'>)

**Comment by jsayles** [comment]
Interesting.  I think this might be part of a greater "internationalization" project that needs to be done.  Are you trying to install this in non-english?

**Comment by erickmendonca** [comment]
Yes. I'm brazilian and I'm trying to run nadine in Brazilian Portuguese. A lot of users have special characters on names.

My current workaround is to add this on local_settings.py:

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by jsayles** [comment]
This should help:
https://docs.djangoproject.com/en/1.7/topics/i18n/

**Comment by erickmendonca** [comment]
Great! I tried it before, but I will try again.

**Comment by erickmendonca** [comment]
Sorry for the late response, but I didn't have success with the i18n. I did, however, changed the database from PostgreSQL to MySQL and the issue is gone.

**Comment by jsayles** [comment]
Good to know!  Do you have this working in production or just poking around?

**Comment by erickmendonca** [comment]
Just poking around, but it'll go to production soon! :shipit:

**Comment by jsayles** [comment]
Great!  Let's move the conversation to the discussion group.
https://groups.google.com/forum/#!forum/nadineproject
