### ISSUE TITLE
Bills Page + Invalid Billing + Has CC = Yellow

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#126]
ON the bills page it shows a red dot next to members that do not have a valid billing profile.  This should be a little smarter and check to see if there is a CC on file and if so it should be yellow not red.  This will help us know who just doesn't have a card in the system yet and who has entered theirs already.

**Comment by laurenmgrant** [comment]
So cool!

On Thu, Mar 19, 2015 at 1:26 PM, Jacob Sayles <notifications@github.com>
wrote:

> ON the bills page it shows a red dot next to members that do not have a
> valid billing profile. This should be a little smarter and check to see if
> there is a CC on file and if so it should be yellow not red. This will help
> us know who just doesn't have a card in the system yet and who has entered
> theirs already.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nadineproject/nadine/issues/126>.
>



-- 
Lauren Grant

Office Nomads
officenomads.com
206-323-6500
