### ISSUE TITLE
Member Alert: Stale Memberships Mute Button broken

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#129]
I have muted Christine Deppe's (and other SCSA members) stale membership alert a couple of times and it keeps coming back.

**Comment by susancevans** [comment]
I muted Madhu, Margo, Rob and Ron's stale membership alerts and they came back the next day. Strangely, the others that I muted did not come back. Hrm...

**Comment by jsayles** [comment]
Is this still broken?  Seems to be working now.
