### ISSUE TITLE
Usage Days Miscalculated when Guest Of

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#132]
Heather Siddiqui has been here 3 times and the first time was marked as a guest of Veronica Smith.  After that we added a Team Membership also guest of Veronica Smith.  This resulted in her usage days being calculated as 4 of 5 days.  The 5 days comes from Veronica's Resident membership and the 4 comes from adding up the 3 drop in days and then adding in again the one day she was a guest of veronica.  

All of this is found in models.activity_this_month

**Comment by susancevans** [comment]
Similar issue still happening - Nicole signed in once for a billable visit and then again as a guest of another member, but the Nadine interface tells her she's used 2 of her 5 days. This is not technically true - she's only used one.
