### ISSUE TITLE
Member Alert: Add Date to Exiting Member Subject

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#147]
It would be nice if the subject of the Exiting Member email had the date they were leaving.

**Comment by laurenmgrant** [comment]
Yes!  This would be very helpful!

On Tue, Jun 23, 2015 at 9:17 AM, Jacob Sayles <notifications@github.com>
wrote:

> It would be nice if the subject of the Exiting Member email had the date
> they were leaving.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nadineproject/nadine/issues/147>.
>



-- 
Lauren Grant

Office Nomads
officenomads.com
206-323-6500
