### ISSUE TITLE
Upgrade Django Registration

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#150]
Current django registration is at 1.1 which works but has deprecation issues.  There is a new version (1.2) that addresses those issues but it has some DB migrations that don't play nice.  Not exactly sure what the issue is yet but the error is:

django.db.utils.ProgrammingError: relation "registration_registrationprofile" already exists

**Comment by pcompassion** [comment]
same problem here. with django 1.8 python 3.4 django-registration-redux 1.2

**Comment by jsayles** [comment]
No longer using Django Registration package
