### ISSUE TITLE
Anniversary Email at 4 years 11 Months

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#152]
That's weird.... should only be year anniversaries....

**Comment by jsayles** [comment]
Actually it turns out that andrew has been here for 1825 days which is 4 * 365 and I'm testing years by doing days % 365 == 0.  This isn't a great way to do it I guess.

**Comment by jsayles** [comment]
Fixed!

**Comment by laurenmgrant** [comment]
Hooray, thanks, J!!!

On Wed, Oct 21, 2015 at 10:02 AM, Jacob Sayles <notifications@github.com>
wrote:

> Fixed!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nadineproject/nadine/issues/152#issuecomment-149963124>
> .
>



-- 
Lauren Grant

Office Nomads
officenomads.com
206-323-6500
