### ISSUE TITLE
Sign-in App: Number of days used calculated wrong with guest days

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#155]
If you are paying for your own membership and you sign in as someone's guest, the following page shows you "You have used X of Y days".  X has all of your days + the guest days.  Instead it should be one of the following:

Signed in not as a guest: 
You have used X of Y days
X = number of days not marked as guest

Signing in as a guest:
You have used X days this cycle as guest of Host
Where X is the number of days you have signed in as a guest of this Host this cycle

**Comment by abkruse** [comment]
This bug is still active. Nicole says she continues to encounter it when she signs in.
