### ISSUE TITLE
Turn off auto-bill bug?

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#157]
Cory Cocker's membership had ended but his auto-bill still went through!

**Comment by jsayles** [comment]
The only time I've seen this the auto-billing wasn't in fact turned off or was turned off after the bill went through.  It's turned off now for sure.  If this happens again next month we can re-open this bug.

**Comment by susancevans** [comment]
I think this one might have been a bug - I'm not sure how else to classify
this. We'd had an email back and forth with Corey on August 10th and
changed his membership at that time. I'd assume that a change in membership
of any kind would trigger Nadine to turn off the auto-bill. That didn't
seem to happen this time, which is why I flagged this as an issue again.

Am I understanding the process incorrectly?

__
Office Nomads
officenomads.com
