### ISSUE TITLE
Add receipt option to auto-bill feature

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#166]
When using the enable auto-bill feature, add the option of sending a receipt and editing the text of the receipt.

**Comment by jsayles** [comment]
Done!

**Comment by laurenmgrant** [comment]
Go, Jacob, go!  Thank you :)

On Tue, Feb 16, 2016 at 1:59 PM, Jacob Sayles <notifications@github.com>
wrote:

> Done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nadineproject/nadine/issues/166#issuecomment-184891905>
> .
>



-- 
Lauren Grant

Office Nomads
officenomads.com
206-323-6500
