### ISSUE TITLE
Credit card description not showing

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#168]
In the USAepay page for an individual member the card description is not showing. BUGGGGGGG.

**Comment by jsayles** [comment]
Odd.  I'm looking today and the description is in there!

**Comment by susancevans** [comment]
That is odd! You're right - I see it today.

__
Office Nomads
officenomads.com

**Comment by jsayles** [comment]
This is fixed.  It was not showing it if auto-bill was disabled.  Now it shows it always.
