### ISSUE TITLE
Wording for guests of members who log in

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#191]
Currently, the login screen asks: "Is another member paying for you today?"

This might be better rephrased as: "Are you another member's guest today?" (or something like that).

We had feedback from a member wanted to host a guest. He did not want his guest to feel like she was imposing costs upon him. Also, it is not always accurate that a member is "paying" for their guest, as they are often using one of their PT-n days, or one of their resident guest passes. 

I think this is a positive change to the language presented to guests.

**Comment by jsayles** [comment]
All for changing the language but I need the exact phrase you want.  The
current wording was an adjustment to make things clearer and in the end
it's really about preference.  Remove the guessing game for me and I'm
happy to make the change.  Keep in mind there is limited space for the text
and a long sentence won't be read fully.

**Comment by mimorita** [comment]
"Hello visitor! Welcome to our space today. We see that you do not have an
account of your own. Are you the guest of another member for this
particular visit?"


Kidding.

This is the language we'd like: "Guest of another member?"

Thanks!
