### ISSUE TITLE
Include "overages" line on bills

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#210]
For a member who gets a bill that includes overage days, it would be useful if there was an additional line on their bill in Nadine that totaled the amount that should be billed for overage days. For example:

Bob has an Advocate membership but went over two days on his last cycle. Bill should appear as:

Monthly charges: $30
Overages: $40
Drop-ins (3): list of dates

**Comment by jsayles** [comment]
I added days, not dollars and I think that will work like we want it to.
