### ISSUE TITLE
Mark a bill as "in progress" 

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#214]
For members who pay by ACH, it would be helpful if there was a way to note that their bill was in the process of being paid so that we don't accidentally bill them twice. Separating them out into a new section would be useful, but minimally some way to visually tell that a member's payment is in process.

**Comment by jsayles** [comment]
I see this being a new boolean field on the Bill model.  When it's flagged the bills drop down to an In Progress section.
