### ISSUE TITLE
Note/annotate the To-Do list

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#215]
It would be useful to be able to add notes or somehow "assign" to-do list items so that it shows that someone is making progress on them. "I'm on it!" or something along those lines so that we know that an issue is in the process of being resolved and/or know who to talk to about it.

**Comment by jsayles** [comment]
The key point of this is a new assigned_to user field on MemberAlert.  

The second part regarding "notes" could be accomplished but linking to comlink staff@ and team@ emails.  We can also use the current note field and just add a "save" button not tied to "resolved" or "muted".

MemberAlerts assigned to people should have their own lists.
MemberAlerts with notes that are not resolved should have their own list.
