### ISSUE TITLE
Email bounces

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#217]
There currently isn't a great way for the staff to be alerted if a new member enters an email address that is invalid. 

For example, a new member (Natausha) just got started but we only discovered that her email address was entered incorrectly when it bounced from the member list. It would be preferred if that bounce alert happened when Nadine originally sends her the introduction email so we're aware that the email address doesn't work.

**Comment by jsayles** [comment]
Nice.  I like it.

**Comment by jsayles** [comment]
I added a hook into Mailgun's soft validation and this in combination with django's email validation should make it hard to enter the wrong email address.
