### ISSUE TITLE
"Invalid Billing" does not show on user reports

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#233]
At /staff/user_reports/ when selecting Report: Users with Invalid Billing

Returns "0 users found", even though there is at least one member in the selected time period with an invalid billing profile.

**Comment by jsayles** [comment]
The time period isn't the date the person's billing went invalid.  We, unfortunately, do not have that information.   Instead it looks at the date the user was created... which is kind of useless.  I think that if you really want this information we need to create another report that does not have a date range.
