### ISSUE TITLE
Reply-to name is wrong

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#236]
When we get an email from the website form, the Reply-To name is "Office Nomads" rather than the person's name. 

e.g.: So when replying to the email, we get --
Reply-to: "Office Nomads" <people.person@mail.stuff>

**Comment by susancevans** [comment]
This is still happening and is causing confusion for us on the staff side (just making sure that we actually replied to someone as opposed to replying to ourselves). Can we bump this up?

**Comment by jsayles** [comment]
This is not an issue with Nadine, but rather NinjaForms.  That's what we use on our website.  Looking at the documentation for NinjaForms it looks like we have set everything correctly but that Gmail does not recognize it.  

From the docs:  "Reply To – The e-mail address which will be replied to is a user selects “Reply” from their e-mail client. (NOTE: Some popular e-mail clients, such as GMail, do not respect this setting.)"
