### ISSUE TITLE
"Disable billing" link does not work on member page

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#245]
A member emailed to say that they tried to disable billing form their nadine profile, but it returned an error message.

**Comment by jsayles** [comment]
Please post the error message to this bug.

**Comment by mimorita** [comment]
The error message was an on-screen message to the member, I do not have the message.

**Comment by mimorita** [comment]
I just tried with another member's profile, message is:
"Ooops!
It looks like there was a problem. Our support staff has been notified."
