### ISSUE TITLE
Photo upload does not work (for some photos)

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#251]
Attempted to upload photo from /member/profile/[USER] and it doesn't work for one user. Which is weird, because it is only an issue with one user's photo. 

Process:
- Clicked the "Edit Photo" link on left side
- Chose file (jpeg image)
- Preview uploaded
- Positioned the selection box on the preview image
- Hit "Save"
- Status bar showed "Uploading n%" until fully uploaded
- Redirected to error at /member/profile/[USER]/edit_photo/ with the error: "ERR_INCOMPLETE_CHUNKED_ENCODING"
- Photo not uploaded to the user's profile

**Comment by abkruse** [comment]
Might just be a local issue with Mike's computer/Chrome. We are going to dig and figure this one out.
