### ISSUE TITLE
User profile link in billing email footer

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#259]
In "Billing Transaction" emails sent automatically for activity from USAePay (e.g. card validation), the footer should contain a link to the user's profile, but the link is wrong.

Footer link now (wrong): https://apps.officenomads.com/staff/detail/USER_NAME
Footer link should be: https://apps.officenomads.com/staff/user/detail/USER_NAME

**Comment by jsayles** [comment]
I've updated the USAePay settings.  This is now fixed.
