### ISSUE TITLE
Deactivate Auto-Bill at end of membership

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#261]
Request: Automatically turn off Auto-bill at the end of a membership.

Request (if above request is infeasible): Add an "Exiting Member" task to turn off auto-bill if auto-bill is still active the week before the member exits. 

Why this is requested:
Member "CT" had a membership that ended on 3/4. On 3/5, she was auto-billed. 
- The membership end date was set in Dec. 2016
- The membership was auto-billed since 12/2016
- There was no change in membership since Dec. 2016, so auto-bill was not automatically shut off
- Staff did not manually shut off auto-bill (since most exiting members have a change in membership within their final month that automatically shuts off auto-bill, staff is not in the practice of checking the auto-bill status of exiting members)

**Comment by jsayles** [comment]
This is done.
