### ISSUE TITLE
User Report: Invalid Billing is inaccurate

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#262]
At /staff/user/user_reports/
- View Report with drop-down menu selecting "Users with Invalid Billing"
- This captures users who also have valid billing.

**Comment by jsayles** [comment]
Duplicate of #233.  This report should be removed because it's misleading.

**Comment by mimorita** [comment]
Not a duplicate, different issue (at least from my perspective). 
The "Invalid Billing" report returns users who have "Valid" in the billing column.
