### ISSUE TITLE
Feature request: iPad alert

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#268]
It would be great to have an alert pop up when a member signs in and has tasks that still need to be completed. Similarly to how now the iPad alerts a member when their billing profile needs to be updated. 

Often when a member signs in who needs to get something done (a new member orientation is a great example), the Team gets the email about that task after the person has walked away. That is one contributing factor to why they take a bit longer to get done sometimes. It'd be nice to include the member in the process so they know they have some things to do still.

**Comment by abkruse** [comment]
Done and will be available in 2.0

**Comment by abkruse** [comment]
Have changed that to 1.8.
