### ISSUE TITLE
Membership Pages:  Date Display

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#272]
In the new membership pages, the dates come in a variety of forms.  Sometimes they are Month Day, Year, sometimes MM-DD-YYYY, sometimes other ways.  We should be consistent throughout.

**Comment by jsayles** [comment]
Nope, not closed.  

members/membership/user:  start date: YYYY-mm-dd, next bill date: Month Day, Year.  

I prefer Month Day, Year as I assume it's more user friendly.

**Comment by jsayles** [comment]
Another that might be hard to spot is on the same page when you are editing current subscriptions.  The existing subscriptions dates are YYYY-MM-DD and the last line has dates in YYYY-M-D.

**Comment by abkruse** [comment]
Ah, ok. Def missed that.
