### ISSUE TITLE
Move Mailing List Subscribe to View/Form

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#276]
Pre 2.0 we had 1 Membership and there was a post_save signal on Membership to automatically subscribe them to the members@ mailing list and invite them to slack when they joined.  This signal no longer makes sense as every member now has only 1 Membership that consists of multiple ResourceSubscriptions.  The logic should be moved to the Edit Member view/form.

if first Resource Subscription:
    invite to slack
If membership is new (there was no membership yesterday):
    add to members@
    # This is problematic if the user was previously unsubscribed from the members list.
if membership is changing (i.e. PT-5 to PT-10)
    do nothing
if membership is ending
    remove from members@
    # you can not remove a user from slack unfortunately

**Comment by abkruse** [comment]
Not entirely sure how to test  this but I think it's right.
