### ISSUE TITLE
Email verification does not work 

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#286]
Link from verification email leads to "400 Bad Request"

**Comment by jsayles** [comment]
I'm going to need more details as I was able to verify emails just fine,
without the 400 error.

Jacob Sayles
Design and Technology Lead
Kanawha Design Studio
https://kanawha.design

**Comment by mimorita** [comment]
It was a member who had just signed up, and clicked the verification code link. He was on his phone when he did it. I watched it happen, and saw the error myself.

**Comment by jsayles** [comment]
This is fixed.
