### ISSUE TITLE
"Paid By" does not list a new member

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#288]
At /staff/user/add_membership/[USER]

New member "SA" is the team lead for a new team. He, and the rest of the team, signed in for the first time today. When I try to assign the rest of the team, SA's name does not appear on the "Paid By" list.

**Comment by jsayles** [comment]
Interesting.   You definitely added the membership first?  It would all be
about the timing.  It will certainly show up by tomorrow but we'll figure
out what is happening with this bug.

Jacob Sayles
Design and Technology Lead
Kanawha Design Studio
https://kanawha.design

**Comment by mimorita** [comment]
Yes, added the team leader's membership first. 

I ended up doing it through the admin interface for the team members today (since SA appeared on the list in Admin membership edit)

**Comment by jsayles** [comment]
I found the smoking gun.  It had to do with a few libraries being out of date.  This is fixed.
