### ISSUE TITLE
Tablet:  Incorrect # of Days Displayed

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#301]
A member has been in 3 days but 1 day is waved.  If you go to the person's sign-in page (Members -> Letter -> Name) it shows "3 of 5" days when it should display "2 of 5" days.  If you go to their profile (Here Today -> Member) it shows "0 of 5" days which is just totally wrong.

**Comment by abkruse** [comment]
Is this issue still happening?

**Comment by jsayles** [comment]
This has been fixed.
