### ISSUE TITLE
"Edit Photo" does not work to replace a photo

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#303]
At /member/profile/[USER]/ a member already has a photo, but I want to replace the photo with a new one.

- Go to "Edit Photo"
- Choose file and click "upload"
- Returns page /member/profile/[USER]/edit_photo/ with the error:
```
This page isn’t working
apps.officenomads.com unexpectedly closed the connection.
ERR_CONTENT_LENGTH_MISMATCH
```

- Go back to /member/profile/[USER]/ and the new photo has not been uploaded.

**Comment by abkruse** [comment]
Fixed. Closed on 2.0 branch.
