### ISSUE TITLE
"$" in deposit leads to error

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#309]
Trying to record deposit for a member via their profile at /staff/members/detail/[USER]/
- Under the "BILLING" tab
- Entered Record Deposit of "$200.00"
- Returned an error. 
- Entered "200.00" (without "$" character) and it recorded properly.

I don't know if this occurs in other contexts when recording money (e.g. receive payment). And it's not actually broken, since the "$" is just extraneous. But there was no indication what the error was (e.g. "Only use numerical!") so I did it a couple times before I tried without the $. So, possibly add a different error, or have it ignore "$", or put a "$" just in front of the text box.

**Comment by abkruse** [comment]
Closed on 2.0 branch.
