### ISSUE TITLE
New member does not show up on open bill list

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#322]
New Advocate member M.F. started his membership this morning. There is no bill generated for him. 

Does the bill not get created until the end of day? 

If so, then new members won't be charged until at least the next day, once a bill is generated.

**Comment by jsayles** [comment]
Correct. It's generated at the same time it used to. Should we bump that
up?

**Comment by susancevans** [comment]
We used to be able to hit "run billing" to manually kick the bills to be
generated if needed. It doesn't look like that's a possibility now - maybe
that would be a useful tool to bring back so we could have bills there if
we want to tackle them right away?

S

__
Office Nomads
officenomads.com

**Comment by jsayles** [comment]
That functionality is still there under Batch Logs.
