### ISSUE TITLE
Change labels for gender

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#323]
Currently in a member's user profile, the options to select under "gender" are:

Unknown
Male
Female
Other

Please change the labels to be:

Unknown
Man 
Woman
Something else

If possible, it would be nice to have the "something else" have a blank that members could fill in but that's not a strict requirement.

Thank you!

**Comment by abkruse** [comment]
I have some thoughts on the wording so let's talk this over in person.

**Comment by jsayles** [comment]
As of 2.0.5 this has been changed to Man, Woman, Something else, Not recorded.
