### ISSUE TITLE
New user does not trigger automated tasks

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#330]
This morning about 9:15, P.K. entered his information on the iPad to create a new user. 

- "New user" announcement email did not get sent to team@

**Comment by jsayles** [comment]
Duplicate of #313

**Comment by susancevans** [comment]
This is still not happening. I'm not sure if I need to re-open this or #313 but is there any chance we could prioritize this this week? It's a pretty important feature for us for the day-to-day.

**Comment by jsayles** [comment]
The bug is still open but I thought I fixed it.  I'll dig further.

**Comment by susancevans** [comment]
Thank you!

__
Office Nomads
officenomads.com
