### ISSUE TITLE
User Report: Ending Memberships error

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#333]
at /staff/members/user_reports/

- Select Report: Ending Memberships 
- Date Range: 7-18 to 7-25
- Returns 3 members whose memberships are not ending JW, DG, PK

**Comment by abkruse** [comment]
Those three were included because they do have an end date to subscriptions but they are starting a new subscription in that time period. Rewritten now to exclude members with new subscriptions in that time period. Closed on 2.0 branch.
