### ISSUE TITLE
Enhancement: Free days for all

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#336]
It could be cool to build in the ability to not bill anyone for an entire day when we do things like all-day open houses. This could be good for 312 as well as there may be promotional days where there will be no bills generated for the day. 

Right now we have to go through and waive all activity individually, but it'd be great to just declare a day that no one will be billed and be able to waive everyone who signs in at once. 

No rush - just an idea!

**Comment by abkruse** [comment]
Closed in 2.0

**Comment by jsayles** [comment]
The way this was implemented is to provide a "Waive All Days" button on the Record Activity button.  This will only work while none of the days are not associated with a bill yet which happens over night.  If you don't press the button before then, or you run a billing batch manually, the button goes away.  

There are better ways we could go about this and I'm happy to revisit the issue again if this solution doesn't work out.
