### ISSUE TITLE
Members not being taken off member mailing list

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#337]
I have had to manually remove members from the member mailing list - it looks like that is not automatically happening anymore. It would be great if that feature came back!

**Comment by jsayles** [comment]
Is this still the case?

**Comment by susancevans** [comment]
Hard to tell. We'll just have to wait for the next member to leave to find
out. Right now the next exit date for a member on the list is August 16 (E.
Russell). So we can wait for her membership to end (she does not want to
renew) and then double-check.

S

__
Office Nomads
officenomads.com

**Comment by susancevans** [comment]
This is still the case. I just checked and there are a few members whose memberships have ended that are still on the list. I'll leave them on there until Thursday in case y'all have time to look into this further.

**Comment by jsayles** [comment]
With the move to Comlink this appears to be resolved.
