### ISSUE TITLE
Past guest membership results in days associated with wrong account

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#338]
Member A.C. checked in today. He is an advocate member, and this was his first check in for several months. The iPad, however, showed that he had used 2 days.

**Comment by abkruse** [comment]
We've seen this bug before, right?

**Comment by jsayles** [comment]
AC used to pay for a membership from IdN and that membership has long since ended.  IdN came in this week and signed in as a guest of RW but for some reason his day got put on AC's bill.

**Comment by jsayles** [comment]
This seems this is not billing related.  It's on the iPad and on the member's profile under Activity but it does not show up on AC's bill.  

The bug is in nadine.models.profile.UserProfile.days_used()

**Comment by jsayles** [comment]
The bug was actually in nadine.models.membership.Membership.users_for_period()
