### ISSUE TITLE
$0.00 payments recorded in billing

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#341]
I'm finding more payments recorded for "$0.00" and I think I have a clue to what happened. 

On bill 13796 for CG there was a payment recorded for 7/2 for $360. There were three separate $0.00 payments recorded for 7/1. 

CG has a team membership for a team of 4. So when it migrated, the payment was recorded for CG, and a $0.00 payment was recorded for each of the other team members. 

I will pay attention and see if this happens with any post-migration bills, but I haven't observed that yet.

**Comment by abkruse** [comment]
Great catch, Mike. Definitely keep us posted on this.

**Comment by jsayles** [comment]
Good observations.  I'm going to close this bug because it seems it's only for migrated bills.  If you do in fact find this happening post-migration, please reopen this bug.
