### ISSUE TITLE
"Overages due" shows a total, but not details

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#342]
At /staff/billing/bills/outstanding/

"Overages Due"
- The total line shows "1 bill $180.00"
- There are no lines above it, so I don't know where that sum is coming from.

**Comment by jsayles** [comment]
This is because of how we fixed a previous bug, in display only.  The real
fix must be done in the query and I'm working on it.  I'll close this bug
when both are fixed.


Jacob

---
Office Nomads - Individuality without Isolation
http://www.officenomads.com -  (206) 323-6500
