### ISSUE TITLE
Member alert for non-active member

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#343]
Former member I.S. signed in today as a guest of another member (K. deL.) and it triggered an alert for him to get a new member orientation. I. was a member (a PT5-promo) and never got his orientation so I'm guessing it just has that leftover task attached to him. But as he's not an active member this alert shouldn't be triggered.

**Comment by abkruse** [comment]
Closed in 2.0

**Comment by susancevans** [comment]
Ian S came in today. Is not an active member and we still got the member alert email.

**Comment by abkruse** [comment]
Ah, so staff still is getting the email but he didn't see the alert himself?

**Comment by jsayles** [comment]
Yes.  The solution we chose was to remove the alerts from the tablet
interface so they don't SEE the alerts.  The alerts still happen.

Alex, I'll take this one.


Jacob

---
Office Nomads - Individuality without Isolation
http://www.officenomads.com -  (206) 323-6500
