### ISSUE TITLE
New "None" memberships

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#365]
When a membership is created in the future it is created as a "none" membership in Nadine. This is fine for the back-end but members are also receiving emails about their "none" membership. This doesn't look good on our behalf. 

Request to have the membership name in tact in the emails so that members know what kind of memberships they have.

**Comment by susancevans** [comment]
This is still happening and it'd be great if the membership type could remain in tact instead of being tagged as "None." That is confusing to new members.

**Comment by susancevans** [comment]
Just nudging this one as it is still happening. Just added a new Resident member today and he got two emails welcoming him as a "None" member. That doesn't really come across well for us. Thanks!

**Comment by jsayles** [comment]
The fix isn't really what we want to do, but it will fix the "None" emails.  I simply exclude the membership type in cases like this where it can't figure it out correctly.  So in the case of a future membership the email subject will be "New Membership".

**Comment by jsayles** [comment]
Updated to look at future subscriptions in this instance.  This is optional and only trigged in the sending of these New Membership emails.
