### ISSUE TITLE
initial installation admin fails

### ISSUE THREAD

**Issue by derekparnell** [nadineproject/nadine#368]
I followed the steps... install vagrant, switch to nadine folder, vagrant up, go to site

Try to login as admin/admin

It fails telling me that the password is invalid.

What now?

**Comment by jsayles** [comment]
You can create a new user with the following command: ./manage.py
createsuperuser

**Comment by jsayles** [comment]
I've also updated the vagrant file so things are looking pretty solid.  Let me know if you are still having issues.
