### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by wadewilliams** [nadineproject/nadine#369]
Hello - 

 It would be helpful if there were a little more documentation around the basic set up/config -- 

 http://nadine.readthedocs.io/en/master/settings.html

 I've got the app up and running on docker locally, but the `manage.py setup` seems to be storing the values _somewhere_ - but not the `local_settings.py` -- the file generated appears to be a simple copy of the `local_settings.example`. Not sure where else this info could be stored - for example, database username defaults to `root`, which is not the same as `postgres` which is what the default user was setup on the pgdb. When I tried to find this setting, it does not appear anywhere in the codebase/repo, so I needed to re-run `manage.py setup`, which seems very strange.

 As my basic install goes, I'm seeing a variety of 500 errors around the site that appear to be from misconfiguration. For example:

`ValueError at /staff/settings/ Need 2 values to unpack in for loop; got 13.`
`ZeroDivisionError at /staff/stats/gender/ float division by zero`

There are other obvious errors that have to do with mail setup, slack setup, payment apis, etc. I didn't bother setting all of those up because I wanted to give the app a test drive without spending too long on configuring all the things. 

Anyways, thank you for publishing this!

**Comment by jsayles** [comment]
Please email me at info@nadineproject.org to discuss.
