### ISSUE TITLE
Email recovery not working

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#371]
Member M.W. tried to reset his email password, but was never sent a recovery email. I checked and he was using the correct address on his profile.

**Comment by jsayles** [comment]
Looks like he was using an Android Phone when he was doing this?  That might be a clue.  

He did get the Verify Email link so we know his email is good.

**Comment by jsayles** [comment]
I have verified the emails are in fact going out.  I used Safari on a Mac to verify this.  I'm thinking something is up with his phone and I'll poke around to see if I hear more.

**Comment by jsayles** [comment]
Same issue as #372 caused by the protocol used in Android phones.
