### ISSUE TITLE
Autobill does not turn off when membership changes

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#374]
Member Joe P. had his PT-5 membership scheduled to end on Dec. 31, 2017. His autobill was set for the first of the month, and it did not automatically turn off when his membership ended, and so he was charged on Jan. 1, 2018. 

It is important to either reinstate the auto-off feature, or know that I need to manually check all lapsing memberships. (Or this could have been a year-end bug, since I think it'd been working before)

**Comment by jsayles** [comment]
Auto-off was not disabled so I'm not sure what happened here.  I'll need to dig in to it more.  Until this bug is closed, please double check to make sure it gets turned off.  This should also give us more data on when it works, and when it doesn't.

**Comment by mimorita** [comment]
It looks like maybe auto-bill is turning off when a membership ends, but not when it changes. For example:

Member J.C.'s PT-5 ended on Jan 16, and the auto-bill turned off.  

Member M.R.'s Advocate membership was set to end Advocate on Jan 13 and begin PT-5 on Jan 14.  The auto-bill did not turn off, and billed automatically for Advocate. A membership change like this used to turn off auto-bill, same as an ending membership.
