### ISSUE TITLE
Stripe Billing Profiles

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#386]
Expand system to work with Stripe as well as USAePay.  Currently the form behind the "Create Billing Profile" button is all wrapped up in staff/templates/billing/action_billing_create.html.  This can be as simple as rendering the right form depending on settings.  

At a future date we can further abstract the payments system to include the intricate reporting currently implemented for USAePay.  To start we just need to capture the credit card for manual processing.

**Comment by tnightingale** [comment]
Some notes on implementation:

- Stripe's [Checkout] feature:
  - HTML/JS snippet produces in-page modal that prompts user for billing information.
  - Info is submitted directly to Stripe's servers and validated.
  - A **temporary** token is returned and passed to a hidden form element which is then automatically submitted to our server.
- Stripe payment Token is temporary _(has a lifetime of minutes)_. We need to use server API to [convert token into a permanent Stripe `customer_id`](https://stripe.com/docs/saving-cards) and save it somewhere.
- Associated with user; 1-to-1 (alternatively could be 1-to-many)
- `customer_id` can then be used to charge card at later date.

[Checkout] by default assumes a transaction will be made immediately. The following parameters override the default modal & form display to communicate that payment info is being collected for later use:

```
data-amount="999" // TODO: Remove this.
data-panelLabel="test"
data-allowRememberMe="false"
data-label="Create New Billing Profile"
```

[Checkout]: https://stripe.com/docs/checkout

**Comment by tnightingale** [comment]
Note: The short-term plan is to manually charge cards via Stripe's web interface. Meaning we don't actually need to save the `customer_id` anywhere. We just verify that the card validated _(though this doesn't actually guarantee that the card will be valid for future transactions)_ and create the customer record in Stripe.

I still wonder whether we should store the `customer_id` somewhere in our system to maintain a link to it's user account for future integration? @jsayles thoughts?

**Comment by jsayles** [comment]
Yes I think we should store it.

**Comment by jsayles** [comment]
This is in 2.1
