### ISSUE TITLE
LDAP Sync on Password Change

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#393]
Login to Nadine
Change your password
Run ldap_sync
observed:  No changes found
expected:  change found and ldap server updated.

I can force an ldap sync (--force) and it will update the server correctly but it does not detect the password change as an actual change.

**Comment by tnightingale** [comment]
Was this on a local machine or on a server?

I just tested this again on my local system and confirmed it to be working as expected. I suspect there's a configuration issue (the configuration is not as straight-forward as it ideally could be...)

**Comment by jsayles** [comment]
I think the key here is that I changed the password in the Django shell.  I was on Nadine01, ran ldap_sync, opened the shell, pulled up the user, called set_password() and save() and then ran ldap_sync again.  I did it this way because the apache install isn't working currently so I couldn't use the interface. 

This is not a usual way of changing a password but it's worth keeping in mind.  I'm going to close this issue and we can review again if this turns out to be a problem.
