### ISSUE TITLE
Cannot log in with email

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#408]
at /login/

Cannot log in to Nadine using an email address.

Enter an email in the "Email" field, and the correct password in the "Password" field, and it returns the error message: "Your username and password didn't match. Please try again."

- Does not work with either a primary or secondary email address. 
- Only allows logging in with user_name

**Comment by jsayles** [comment]
This was an issue the came up when upgrading to Django 2.1.  They handle login slightly differently.
