### ISSUE TITLE
Membership Agreement Signing does not work in iPad

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#410]
On iPad app, USER > Sign Documents > Membership Agreement

Brings up the "Ooops!" error message. Members cannot sign any documents on the iPad.

**Comment by jsayles** [comment]
Turns out Django 2.1 breaks the iPad signing.  I reverted the live server to 2.0.9 and it works again.  I'm pushing this to the Nadine 2.1 milestone when we'll be running Django 2.1.

**Comment by jsayles** [comment]
This is now working.  I had to fork the version of django-jsignature we use but all is good now.
