### ISSUE TITLE
Daily Charge billing record alert for wrong amount

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#414]
At staff/billing/charges/[DATE]

Under the "Action" column
Press the "Record Payment" button

Alert pops up "Bill for USER marked as paid for $XXX"
- The amount "$XXX" is wrong
- But the correct amount appears to be credited to the bill. Error is only in the popup alert.
- (Popup seems to display the sum of all bills displayed, not the individual bill marked as paid)

**Comment by susancevans** [comment]
Duplicate issue of #417
