### ISSUE TITLE
Email verification links broken

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#418]
Multiple reports of email verification links (for new users) going to error page. This seems unrelated to the known Android browser bug. 
<img width="715" alt="office_nomads_not_found" src="https://user-images.githubusercontent.com/18664678/53831629-1b4a0680-3f3a-11e9-81b4-8b6abca1f0d4.PNG">

**Comment by jsayles** [comment]
This is not an across the board bug because I've been able to verify email addresses.  There must be something more going on here.  The Not Found error will show up if you enter an email ID that isn't valid.  If they got the email I doubt that's the case.  I need more context to reproduce this.

**Comment by mimorita** [comment]
New user today also got errors with all browsers when trying to verify.

**Comment by jsayles** [comment]
The link was defaulting to http not https.  On the iPhone, using safari, the redirect was not working and this gave an error.  On a Mac, using Safari, it redirected fine.  I changed the default link to be https and this will fix the problem.

**Comment by susancevans** [comment]
__
Office Nomads
officenomads.com

Woo hoo! Thanks!!

S
