### ISSUE TITLE
New Membership emails not sending (in some cases)

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#425]
New Member emails were not sent to team@ for two recent memberships. Both memberships began mid-cycle of the prior membership, as detailed below. 

User 1685
- Had an Advocate membership with a billing date of the 14th
- Earlier in the month, I added a new PT5 membership, which was set to begin on 5/14 (and end the Advocate on 5/13).
- On 5/13, I went to Admin interface and changed the Advocate to end on 5/12, and the PT5 to begin on 5/13.

User 2242
- Had an Other (mail-only) membership with a billing date of the 6th.
- Today, 5/14, I added a PT5 membership to start today, and end the Other membership 5/13.
- In the Admin interface, changed the bill date to the 14th.

**Comment by susancevans** [comment]
This is still happening. Today member Tyler B wanted to end his current membership mid-cycle and begin a new Team membership to align with new team members joining him. 
No new email was sent.

**Comment by jsayles** [comment]
This logic has been updated and will go out in the next release.
