### ISSUE TITLE
unable to access Demo version.

### ISSUE THREAD

**Issue by meaziz** [nadineproject/nadine#439]
Hey guys,
I just stumbled upon the project and was trying to give it a try.
I used the docker-compose on tag v2.2.3 I got the application running but I Can't find the admin account or any user credentials on file.

any idea how to seed the database if it is not? 
what are the credentials for the different user types?
Or
where is these data documented?

**Comment by jsayles** [comment]
The docker file is 4 years old so your milage will very on how useful it is.  I should have been updating it with every release but I haven't been.  

As for how to create a user you first need to create a superuser from the command line.  Details can be found:  https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-createsuperuser

The base install is not really a demo as it doesn't have any data in it.  You still need to load up your membership plans and such and add/import your users.
