### ISSUE TITLE
Need more documentation for production environment.

### ISSUE THREAD

**Issue by Midna3689** [nadineproject/nadine#440]
Hello, i have been exploring nadine functionality quite in depth but i cannot seem to understand the production part of the documentation. Is it possible to add more steps and details how the deployment process on nginx would be? or even on apache2 ? i'm deploying it on local server but want access to it online via IP address.

**Comment by jsayles** [comment]
Yes documentation is very much needed although it's not a priority at the moment.  I'm always looking for collaborators if you would like to help out.  One thing that would help me make this a priority is if you were open to helping out.  Email me at jacob@kanawha.design if you are interested in exploring this.

Aside from that there is much documentation available out there on how to run a django application in production on Nginx and Apache.  You will find that 80% of what you need is there and I've tried to make the docs we have reflect that final 20%.
