### ISSUE TITLE
Requirements.txt missing 

### ISSUE THREAD

**Issue by anirudhmarc** [nadineproject/nadine#451]
Hi the requirements.txt file is missing from the repo

**Comment by stevensegers** [comment]
I ran into this problem as well while trying to follow the quickstart guide: https://github.com/nadineproject/nadine/blob/master/docs/quickstart.rst

I saw requirements.txt was removed on nov 2 in a commit titled "using Pipfile only":
https://github.com/nadineproject/nadine/commit/73bb66f7212c180bf9bb58a8bf116c2e048c6212

So I guess the issue should be renamed "Update quickstart guide to use pipenv"?
