### ISSUE TITLE
Error "Run these scripts to setup nadine" in quickstart.rst

### ISSUE THREAD

**Issue by tomasjr7** [nadineproject/nadine#454]
Hi, I am interested in testing nadine and maybe collaborate with the project, but I tried to install Nadine following requirements.rst and quickstart.rst, but in quickstart.rst the command line ./manage.py setup returns a django error, even though I followed all the steps, later I installed the latest version of django and the error persists

`Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
`

I'm run Debian 10

**Comment by jsayles** [comment]
That looks like you don’t have your virtual environment enabled.  If you are using virtualenv it will be something like source bin/activate or if you are using pipenv you need to do pipenv install followed by pipenv shell.  The docs are inconsistent and need to be updated.
