### ISSUE TITLE
PW reset email in list

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#99]
Move the PW reset option to the drop-down list of emails we can send to members. Right now it's in their profile view, which isn't as logical (at least to me!) when looking to send a PW reset email.

**Comment by jsayles** [comment]
It's tricky to try to get this in the actual dropdown email list but I did put a link right above that list that clearly states "password reset".  This is all in the email tab of member detail which is where you instinctively look.  I'm hoping this is an adequate fix.
